apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-podcasts
spec:
  accessModes: [ "ReadWriteMany" ]
  capacity:
    storage: 500G
  nfs:
    server: "192.168.1.121"
    path: "/mnt/array/Podcasts"
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-podcasts
spec:
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 500G
  storageClassName: ""
  volumeName: nfs-podcasts
