apiVersion: ENC[AES256_GCM,data:m/c=,iv:N1HPw4G6m3a80pYvjYEc68JDbqzT7THQj1C1GTfiO38=,tag:xt35QjyD1NDWATEHbi48oA==,type:str]
kind: ENC[AES256_GCM,data:ARtJhRsK,iv:BbNnZ9Q/JB8ZwA5Yqlj53Y9WoE5RQcembmeoaxvC9PI=,tag:c9SmYiGxQAKCLn7bOb3gmQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wW0AqlWQxag1V4CLyrnNgYtiqLmXxBI=,iv:uzPO1liGka5dmojIHwsg/HB0T9qj6XVpB4GoU437Jyc=,tag:M2XosDJU9dC/17YdfMMfwg==,type:str]
    namespace: ENC[AES256_GCM,data:YjRgWYchNPNPBaUmIThX,iv:kuCTk8bR2YIchkhqJ6HpN6jPMFgegkTfeheeZA0iKfc=,tag:xUJYMtGOyVQ03PG1LX2pyg==,type:str]
type: ENC[AES256_GCM,data:4xP0akXl,iv:JtMVOkcTZLWuG43rb9WsIlJHM+wKMi3qmibdcUi2OL8=,tag:IcWn1jFhhDxC9eTn/iJJZQ==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:LTj4IwTmMTRSY9gXkZf8o5M2R6oag6M2rGQ=,iv:KxPcFBxfdqNaXPG+K4Ko6LLl91LOziqWYmd+iZnU4vo=,tag:gsmEizYj/Tn93Aq190V6Bw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:bGYoJanUG3y2EeU6422rSHRwwKtWpRQWl+4=,iv:N3piF25VZlhxMXiGOclKGTZHYnUJvIZiQ74akWXpFYw=,tag:/iecMUNuXzhYojKG5k6P/w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JSdAdIikdCPSiJdPp4++QWZkQbsRvrdrlRW0gvTthoV57O7jJnzgx0O+gFSA8xLoEqN8Nu1Ox6pM7HPYR1bukA==,iv:BK/mjwQ09K9J2b9lfBKl2plNks1Xr0qGn/utXp4VB14=,tag:7pPiQf19UBmPakr/zCugrg==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Vkl3M3JvNEh0MjJ4am1p
            RTAvczUxY1haTHhlOFJYSVZFLzhVS0RQQzNJCjZsYlFTS0pkRU9sMEhyRHlvUkh6
            eXlnb2dldTFaeDlnd2lRWVpmd2o0NmsKLS0tIG1lNGV3S3hFUUZLSkVKK1ZoYmFP
            K2xzbDByQ1hNRGZpVWtnQm1NaXlyU2MKzJEbjxDGOsP2uEgvCei9e/MzC1ACiIar
            omvk1siQYfHpCpiZG7Oux5NaLWFRJENGTMxw6cIGv4skTYLCHzl9Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T13:20:29Z"
    mac: ENC[AES256_GCM,data:oheaJhEBmOkh4bi9H4FGNKDd3RtXXKWSv8uiRhf3VG3JGIWOLqE0PKQaj/utEakiLXLIEyeQTaj6U5YZMiLmVI/mhZ4+utSHuA7cIQk/IymHi0EB4ZnVwpZQSIUd+m9RTn8cZEldgpb0EqWieTMDEFo2dbdFfHS2ccH1aaypItg=,iv:TVIxYbfJ0maA3V1MCwJiKgNbxV3jY69y/+h/bLq8u+A=,tag:BsfzJK1zl4CQMZqO5krljg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
