apiVersion: ENC[AES256_GCM,data:LOk=,iv:BNNdGzblkjX16pronHanp5Ifs4gfkV6kqZ4/V8pF7q4=,tag:CdnRy1n3dguJpzdUYcc6OQ==,type:str]
kind: ENC[AES256_GCM,data:BmTK3lGj,iv:6xEYXbRoINOAjSNnfBh4ZNMT5SHmeUT27178kWHDxO0=,tag:mhmEvYQOa7aRMnllEgaYyg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RVyMM37TZANrpEnDiHqrIX7DRQ==,iv:vCPgrqhu5Gt98OZUEay7mDyVqMyZ5mzUuABre59vPws=,tag:gAFx2kETo0XkIXgdVu4LkA==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:SxsqxVzgYC+iBwzjVV6rCJgpCg10lOfeApOTbC17fuCF2EzcM3GaXXpmym1lffgbJwAHR52kfa5sqy9IsVDeqpcGJgS6+0FNPI2wHkI4PfMNWDsYb2oGJ4JjOTbW/ybu,iv:kBlYsebHKDsK2ExUmmLFsw+3h/ufVydllQBgAlWpHVw=,tag:sPJzW+fEjBBLZ6lB6K8GOg==,type:str]
    #ENC[AES256_GCM,data:Zqi/YuFANwoINMFFw9QMGOIxlnBdkX9XwuufPtH1cCjAcZ/Nq6y070c+UtFIvnGSsHjT4Envng==,iv:Bx51o99p1E8NQEoCvOg35iiVm9ADGPfc0bH+axBA8U0=,tag:GgClqK6OuGB/e6/jmplZCQ==,type:comment]
    ADMIN_TOKEN: ENC[AES256_GCM,data:n7/TRhJz07/sA0M72XYLuQtYZbPwWkvZ1lthlo/LdFF8P2uAUXQLpca/9ktvb51LtW3DgmWZMWQJN3jZAUl8hF9F/Fi/mVT3VrzLj7BHAsBM/EkBb2vBLockWUVIff/93mw4jMAemdt3uqAEhVgYXHYMmzdyyw==,iv:1arMD1QABQxCqeguw+B0n3OwV5K04ljfBynAu8kbdls=,tag:a3y0y83vhFSCtM2M2L3+wQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:UfXo4DnxdqhTngp71Q==,iv:uk3iDwdf2ov52UXV3baV3n5pDwXL8asEvq00v5fJ2mQ=,tag:MsjktD0HSThbTbnAhkR9Pg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:0NR8Byi42bV5EffqBOeWQQ==,iv:W2k+lHeyE/zwgr9HW6T6yZC/ld/tKmnpXKQ4BSXrhDQ=,tag:WQNPESKMLkGr7g9nky5w9A==,type:str]
    PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:3dJcF7bm0+bIC3Y8t5/1U3KauDKakHhyp/wSEyjjcgkDjfqA,iv:JagCG7cTgintHRRkxldSzKSSHyBI7LpvBNV662d4Ulw=,tag:8dFzVjWkt/nXM3DX7/C11Q==,type:str]
    PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:y47vx1ZLsmSzbcf1nDeDDQf/WZM=,iv:zBL8NBWrP9plyTP1sywfTmXol66vILKVbJy1zWWeeqA=,tag:OB0n3g5Qf/C7RBvHmOgwHg==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkU3JreWVEU21tY2RnNmI5
            bnZHYU1DK0k5bENUTEhCZXFSOGtqQVRCVUJJClFJZGRnRWtkZXFXZ3dZOVRoYndn
            MHVMb0NHb2dUU1A0V2h1eDdvb3ROZnMKLS0tIEJJNmU1VUVuUzVISmhVYkp0ekJ3
            OWZyYXF6UzBFd0FibTg4cmRTcUwxMm8KXzuuHINwGGPMzK+UlG7Q45zWxqXzIYbA
            YPjzErs7N9vzZlm+00tpzGci9+SL1dU6HE3cldUHApxX2jQibq/zrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T15:28:09Z"
    mac: ENC[AES256_GCM,data:iMZNC5qlpO+wee6ukeYk7bpZazxPqzgylKvry4C2LxKhpAVNq6PoRQJ1EDpGMafy9JiYshaiES5VH+zUSh/cfI5ii84YPNx1w/LoIAMUyRGuuewCU1MHCNHPtjgPpFPaVJ4UVMwyiqbLNoNW8wUHfCneSZuK9EkNJd3pTbkEvcs=,iv:OUBC5G9V3L1vcCWbxGF7E2dZ/3EprUvim97nlWKl7r4=,tag:Qv0CkoDK2ueFMq5XjcLWsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
