{
 "title": "Pihole DNS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pihole Blocking Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_status", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Domains Being Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_domains_being_blocked", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Replies by Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (hostname, type) (pihole_reply)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Ads Blocked Today",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_ads_percentage_today", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Unique Domains Seen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_unique_domains", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Unique Clients Seen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_unique_clients", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Queries by Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (hostname, type) (pihole_querytypes)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Top Domains",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (hostname, domain) (pihole_top_queries)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Top Ad Domains",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (hostname, domain) (pihole_top_ads)",
     "legendFormat": "{{domain}}"
    }
   ]
  }
 ]
}