apiVersion: ENC[AES256_GCM,data:lL8=,iv:7snqyGShaJA8eKgHV1euQB1VPR89wN+uV+7dzv6wvTA=,tag:iHDJNBC7Z8JAAUrGx/ji8Q==,type:str]
kind: ENC[AES256_GCM,data:UiitvJTe,iv:kHIFmkww9aKnwdnHBVmBgYziR6y8SlaPB3LqVFJY+dc=,tag:zZ9jRNokIVB83NNG2FXf8g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VS1lHvcJsnjPa0508ZE=,iv:teWzBPdO3JCpYCrT0ju1YfWFNOUkeEotOFLVy9P5d24=,tag:RLOXPnSVspbOENUtFrIY+A==,type:str]
stringData:
    ND_PASSWORDENCRYPTIONKEY: ENC[AES256_GCM,data:TtkVr2rYys7/bYuVG8nSMA4IYZnG/O8bz54epFpfC7c=,iv:skmx2jytwvqO9BDCUAlDnvCfHRkPSdvJZm1Uh8gIN3U=,tag:iioCqdNp3DXy5XKIk/c6VA==,type:str]
    #ENC[AES256_GCM,data:hBp/Y7pUsmvSO4nlqPzYdm+Xg4+4ZIB6atH/Zd8cOtQA1Aft6cZMy8qcguGHMwm/zRzXRc3yCcrAawf0YDenoQYbdB0=,iv:j4h8QZwgrAbywddobYt5gWphA6wmw75gdAtEmg2JRKg=,tag:Sdon+ZUxpIQF1geGwgFj1Q==,type:comment]
    ND_LASTFM_APIKEY: ENC[AES256_GCM,data:B/gg/pznNF7qn7sGmfhB1489iiGGI+CUikp3axlJgjc=,iv:wsOZxjSyE90LbOTLINMvjgy46SMppYPcrM1ssiAK4us=,tag:JFAoLmw93FejzvcTKg6xLQ==,type:str]
    ND_LASTFM_SECRET: ENC[AES256_GCM,data:jawNj6LHWgX36QTTgDb6GUKK3RGGuc3vbGA6y5vsRa8=,iv:r763rR87fpv6W+s3xPlwRFjkZH3BY6LcQ6VomGfjeHw=,tag:cCtWoBR5Few/6qxx8BMiig==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQWJxTFdyL3ZQQ0t5elhy
            ZDY1bG1wV3FtcHQzUDVZT2h5TFlLM2RmcWowCmpKc0J0QVdkLzJPRmM5WFNubmVS
            NDdaK0NzVCthMndjbUtyMWdVT0x6QVkKLS0tIFZ3dU95YlJUZjlIUjFHT21PU3VC
            RGVaNVREeWVIazM0UWY5UHQ3Tkp4NFkKR9EStvCj9vyn7xLZBVMh/vNoZZb/XZJZ
            X/l8GIKB/I4CE2TJ3tXiYcbzMFu/DXUnKbeonFDCGgeZiKfC6nnoSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T15:20:06Z"
    mac: ENC[AES256_GCM,data:lFf2oH9kOvaQzgnzL/rYq6HPUaAtfIuywonTEHxcLMyAfbUWybWdnrPLWPDIb3JF8jxC72utjhFio4ms3qjxlA5dAE6Z8r5y7FI91pAaLOD7GvrMIszb0X3hJckZSxF+iKaXsQ3FM43jJVo3pFm6HQMKv/E7vGdLONgKZXFd4yg=,iv:iT7nIqVHT8p8skq/nG8XcUkMwOGLr74kyGV7qu4icvM=,tag:empQKUQ+scaXmIZWiApIyA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
