apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: authelia
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8mb4
  collate: utf8mb4_general_ci
  cleanupPolicy: Delete
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: freshrss
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8mb4
  collate: utf8mb4_general_ci
  cleanupPolicy: Delete
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: lldap
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8mb4
  collate: utf8mb4_general_ci
  cleanupPolicy: Delete
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: nextcloud
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8mb4
  collate: utf8mb4_general_ci
  cleanupPolicy: Delete
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: vaultwarden
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8mb4
  collate: utf8mb4_general_ci
  cleanupPolicy: Delete
