apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-authelia
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL"
  database: authelia
  table: "*"
  username: authelia
  host: "%"
  cleanupPolicy: Delete
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-freshrss
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL"
  database: freshrss
  table: "*"
  username: freshrss
  host: "%"
  cleanupPolicy: Delete
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-lldap
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL"
  database: lldap
  table: "*"
  username: lldap
  host: "%"
  cleanupPolicy: Delete
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-nextcloud
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL"
  database: nextcloud
  table: "*"
  username: nextcloud
  host: "%"
  cleanupPolicy: Delete
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-vaultwarden
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL"
  database: vaultwarden
  table: "*"
  username: vaultwarden
  host: "%"
  cleanupPolicy: Delete
