apiVersion: ENC[AES256_GCM,data:RHY=,iv:CHZj5bMOhKrBBmgjZB1UASl3MZY7K4H+EirUq0W10vY=,tag:pC0VQenLT4IGxEyNE7rHZA==,type:str]
kind: ENC[AES256_GCM,data:UHkUXH9O,iv:zLX0vCx9rIWGJ2WyUbtJ/oA2hTifIKv/VDbWtcxI98g=,tag:GaL+DIuHIUdwXLpX8DH+Rg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+pZXrFpnqzCohpJ1BM6E,iv:9QQ1iw2uIqyeQvybinHjL0B91U6KnvqHYqeY0Xh55mQ=,tag:47wUop5l0QNPf9Fcc0nSLw==,type:str]
    namespace: ENC[AES256_GCM,data:9gRx8zd8IkI=,iv:WuyT1IMcpE8ZUH6VextmrlNf3LwiaBlbeeVx9CdARGU=,tag:3CfS1pvcsuv8+vOssVCxcw==,type:str]
stringData:
    root-password: ENC[AES256_GCM,data:ZfJkEdI592uCfAgCaUVPWJHBXc/P,iv:GxYFzR0vjPv43nAkIjDMB9GNNE+0Tzf5gUGNa3a68ys=,tag:yq/ypMxPWTAsGgXZfxDlng==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOHVEbm15TzZ4RHYwTTRj
            QWpSeURleUQyNWpvV0xnSUM3T1ROYTJSTFJvCnkrNEhuL09Hd0F3eTVISC9nQzZC
            M1duRHpsQy9WVUd4bUx4eDlYRWhRalUKLS0tIGpkZG5ReGk3OGJqWXN4VFRaWGha
            ZXlLSnJoTm15a1dxT2JSMHg3ZnZVbWMKWPsvdi3xjK/Rl44BqcvdMsCkb0lXlkG4
            5uKbR5jXKGGE64/2tF+AYHCz3oWQn1BhJgiQPxfQx5y91OoiaelPgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T13:48:48Z"
    mac: ENC[AES256_GCM,data:t30YviV7wv3FsMhBifL947d7NcJiW7NHC1w+cZtVTxCSW2HU7nz5idzn9pYn804yqZaqH5/ovBBRifTZ3JWV66g7nWDl7KmG9nwyAiaMR5z9nl9Fc3Bpz3FZRjWxY0neiNnZnZOaBtRkRdnYWPl9WNEv6XnbZEno4V70xzHmM4A=,iv:qg/UIxaREmgeoYRf9684wEamiMI5Tz5EVZGd3a6GERk=,tag:ykzv2S72MWDcpwOiYoWnKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:RHY=,iv:CHZj5bMOhKrBBmgjZB1UASl3MZY7K4H+EirUq0W10vY=,tag:pC0VQenLT4IGxEyNE7rHZA==,type:str]
kind: ENC[AES256_GCM,data:UHkUXH9O,iv:zLX0vCx9rIWGJ2WyUbtJ/oA2hTifIKv/VDbWtcxI98g=,tag:GaL+DIuHIUdwXLpX8DH+Rg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zgaIgr3YpmFGBjzV490=,iv:cwdWIQXZTCSZcYQXCFnqxDA3F1mAKHmaB4Inl3w34TU=,tag:ZHqvrRMKq0zxOz+8FhAIZQ==,type:str]
    namespace: ENC[AES256_GCM,data:9gRx8zd8IkI=,iv:WuyT1IMcpE8ZUH6VextmrlNf3LwiaBlbeeVx9CdARGU=,tag:3CfS1pvcsuv8+vOssVCxcw==,type:str]
stringData:
    access-key-id: ENC[AES256_GCM,data:bkqIUxpzcfC2jU1D/bMVmN7e+VADcHQn30c=,iv:WKuvz5Fwl31TYPi5wVDJIlTUVLocaag4BlxOvYiV9r8=,tag:hy4+iEHzy9a+VRTX3xhNAw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:1R2GhpvR46u1Zubri48rJyXsaHgwg5AZFAuKsXVp6tXvefuFkuesx/4Jh7eBIkn3VlWdJLmGrAADhN2EzpEliQ==,iv:FIoWUgmxi+EYYcprwkkhoNA9mW7DlH9KFCEOGzDLEOE=,tag:EHi8g64OwPEkMJFE/eEy7A==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOHVEbm15TzZ4RHYwTTRj
            QWpSeURleUQyNWpvV0xnSUM3T1ROYTJSTFJvCnkrNEhuL09Hd0F3eTVISC9nQzZC
            M1duRHpsQy9WVUd4bUx4eDlYRWhRalUKLS0tIGpkZG5ReGk3OGJqWXN4VFRaWGha
            ZXlLSnJoTm15a1dxT2JSMHg3ZnZVbWMKWPsvdi3xjK/Rl44BqcvdMsCkb0lXlkG4
            5uKbR5jXKGGE64/2tF+AYHCz3oWQn1BhJgiQPxfQx5y91OoiaelPgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T13:48:48Z"
    mac: ENC[AES256_GCM,data:t30YviV7wv3FsMhBifL947d7NcJiW7NHC1w+cZtVTxCSW2HU7nz5idzn9pYn804yqZaqH5/ovBBRifTZ3JWV66g7nWDl7KmG9nwyAiaMR5z9nl9Fc3Bpz3FZRjWxY0neiNnZnZOaBtRkRdnYWPl9WNEv6XnbZEno4V70xzHmM4A=,iv:qg/UIxaREmgeoYRf9684wEamiMI5Tz5EVZGd3a6GERk=,tag:ykzv2S72MWDcpwOiYoWnKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:RHY=,iv:CHZj5bMOhKrBBmgjZB1UASl3MZY7K4H+EirUq0W10vY=,tag:pC0VQenLT4IGxEyNE7rHZA==,type:str]
kind: ENC[AES256_GCM,data:UHkUXH9O,iv:zLX0vCx9rIWGJ2WyUbtJ/oA2hTifIKv/VDbWtcxI98g=,tag:GaL+DIuHIUdwXLpX8DH+Rg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UhnjVixj3waEXErFGWp6ew==,iv:HhQ0kK+ggCgmTugHAFdhIO7ibbpgTPiXmG3iX5/oAiM=,tag:4FyXrgK1JFdKGBTjjoJSWg==,type:str]
    namespace: ENC[AES256_GCM,data:9gRx8zd8IkI=,iv:WuyT1IMcpE8ZUH6VextmrlNf3LwiaBlbeeVx9CdARGU=,tag:3CfS1pvcsuv8+vOssVCxcw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:VbVmwDNJXwQb8RMQX8n0NtR/g9KP427zribJ1zU=,iv:2jcPSaKHwX3hgoMgdLGaeiFH3S+7NLNBQZGqgMwRh5A=,tag:TIxt2Wg4HOKvopF/7ubRpw==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOHVEbm15TzZ4RHYwTTRj
            QWpSeURleUQyNWpvV0xnSUM3T1ROYTJSTFJvCnkrNEhuL09Hd0F3eTVISC9nQzZC
            M1duRHpsQy9WVUd4bUx4eDlYRWhRalUKLS0tIGpkZG5ReGk3OGJqWXN4VFRaWGha
            ZXlLSnJoTm15a1dxT2JSMHg3ZnZVbWMKWPsvdi3xjK/Rl44BqcvdMsCkb0lXlkG4
            5uKbR5jXKGGE64/2tF+AYHCz3oWQn1BhJgiQPxfQx5y91OoiaelPgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T13:48:48Z"
    mac: ENC[AES256_GCM,data:t30YviV7wv3FsMhBifL947d7NcJiW7NHC1w+cZtVTxCSW2HU7nz5idzn9pYn804yqZaqH5/ovBBRifTZ3JWV66g7nWDl7KmG9nwyAiaMR5z9nl9Fc3Bpz3FZRjWxY0neiNnZnZOaBtRkRdnYWPl9WNEv6XnbZEno4V70xzHmM4A=,iv:qg/UIxaREmgeoYRf9684wEamiMI5Tz5EVZGd3a6GERk=,tag:ykzv2S72MWDcpwOiYoWnKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:RHY=,iv:CHZj5bMOhKrBBmgjZB1UASl3MZY7K4H+EirUq0W10vY=,tag:pC0VQenLT4IGxEyNE7rHZA==,type:str]
kind: ENC[AES256_GCM,data:UHkUXH9O,iv:zLX0vCx9rIWGJ2WyUbtJ/oA2hTifIKv/VDbWtcxI98g=,tag:GaL+DIuHIUdwXLpX8DH+Rg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lC0cmnN2PHsUe7dqhIE/cg==,iv:hIRopci9Tn+G/oZpP1/EUifzPAgFKrOJDlPQkfeyp4U=,tag:YkKzIxVbUBR2WCVge6XlEg==,type:str]
    namespace: ENC[AES256_GCM,data:9gRx8zd8IkI=,iv:WuyT1IMcpE8ZUH6VextmrlNf3LwiaBlbeeVx9CdARGU=,tag:3CfS1pvcsuv8+vOssVCxcw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:P2EooFcnnYZdDIe8/vGKIj6w2PwUzHXMFhg=,iv:QyD4xphKdxOfQnkVOv1S+SQXKavEf6BuesQa0GMqCMg=,tag:bWk2uDaFnhJvTKotUrSiXA==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOHVEbm15TzZ4RHYwTTRj
            QWpSeURleUQyNWpvV0xnSUM3T1ROYTJSTFJvCnkrNEhuL09Hd0F3eTVISC9nQzZC
            M1duRHpsQy9WVUd4bUx4eDlYRWhRalUKLS0tIGpkZG5ReGk3OGJqWXN4VFRaWGha
            ZXlLSnJoTm15a1dxT2JSMHg3ZnZVbWMKWPsvdi3xjK/Rl44BqcvdMsCkb0lXlkG4
            5uKbR5jXKGGE64/2tF+AYHCz3oWQn1BhJgiQPxfQx5y91OoiaelPgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T13:48:48Z"
    mac: ENC[AES256_GCM,data:t30YviV7wv3FsMhBifL947d7NcJiW7NHC1w+cZtVTxCSW2HU7nz5idzn9pYn804yqZaqH5/ovBBRifTZ3JWV66g7nWDl7KmG9nwyAiaMR5z9nl9Fc3Bpz3FZRjWxY0neiNnZnZOaBtRkRdnYWPl9WNEv6XnbZEno4V70xzHmM4A=,iv:qg/UIxaREmgeoYRf9684wEamiMI5Tz5EVZGd3a6GERk=,tag:ykzv2S72MWDcpwOiYoWnKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:RHY=,iv:CHZj5bMOhKrBBmgjZB1UASl3MZY7K4H+EirUq0W10vY=,tag:pC0VQenLT4IGxEyNE7rHZA==,type:str]
kind: ENC[AES256_GCM,data:UHkUXH9O,iv:zLX0vCx9rIWGJ2WyUbtJ/oA2hTifIKv/VDbWtcxI98g=,tag:GaL+DIuHIUdwXLpX8DH+Rg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pEzk6bhq4LjJUOfPHA==,iv:jJYgE51+2dOZ2ft+x7zMW+eisYFkzd5v7+1fGjxNdbs=,tag:jwsTt/F21kRSf6EXtUANgQ==,type:str]
    namespace: ENC[AES256_GCM,data:9gRx8zd8IkI=,iv:WuyT1IMcpE8ZUH6VextmrlNf3LwiaBlbeeVx9CdARGU=,tag:3CfS1pvcsuv8+vOssVCxcw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:gXNDL4PfRu3+q8bm438Z3l4TcB+rYyP2VQ==,iv:pXCIJu5c16ptdws1XewCYzsu3aK2SMLS/OPkjYWYwW8=,tag:vojPWZzyOabEo+WDGqHcRQ==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOHVEbm15TzZ4RHYwTTRj
            QWpSeURleUQyNWpvV0xnSUM3T1ROYTJSTFJvCnkrNEhuL09Hd0F3eTVISC9nQzZC
            M1duRHpsQy9WVUd4bUx4eDlYRWhRalUKLS0tIGpkZG5ReGk3OGJqWXN4VFRaWGha
            ZXlLSnJoTm15a1dxT2JSMHg3ZnZVbWMKWPsvdi3xjK/Rl44BqcvdMsCkb0lXlkG4
            5uKbR5jXKGGE64/2tF+AYHCz3oWQn1BhJgiQPxfQx5y91OoiaelPgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T13:48:48Z"
    mac: ENC[AES256_GCM,data:t30YviV7wv3FsMhBifL947d7NcJiW7NHC1w+cZtVTxCSW2HU7nz5idzn9pYn804yqZaqH5/ovBBRifTZ3JWV66g7nWDl7KmG9nwyAiaMR5z9nl9Fc3Bpz3FZRjWxY0neiNnZnZOaBtRkRdnYWPl9WNEv6XnbZEno4V70xzHmM4A=,iv:qg/UIxaREmgeoYRf9684wEamiMI5Tz5EVZGd3a6GERk=,tag:ykzv2S72MWDcpwOiYoWnKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:RHY=,iv:CHZj5bMOhKrBBmgjZB1UASl3MZY7K4H+EirUq0W10vY=,tag:pC0VQenLT4IGxEyNE7rHZA==,type:str]
kind: ENC[AES256_GCM,data:UHkUXH9O,iv:zLX0vCx9rIWGJ2WyUbtJ/oA2hTifIKv/VDbWtcxI98g=,tag:GaL+DIuHIUdwXLpX8DH+Rg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jGp6aV9HKTaeUgnBpn50YXM=,iv:NoBOJEPwaUB2nbSlxw3+yju64pU7IKoqpWNmw8a7wWI=,tag:FDYYggz/ryawhd6m55WVJg==,type:str]
    namespace: ENC[AES256_GCM,data:9gRx8zd8IkI=,iv:WuyT1IMcpE8ZUH6VextmrlNf3LwiaBlbeeVx9CdARGU=,tag:3CfS1pvcsuv8+vOssVCxcw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:BnbBJgN1HQ0L2820NpNWdoUR8GVN,iv:YfQoJtcS9QZckU3RB7tCHqShVIssA0yMULTKBxLupNc=,tag:hLqQJi/gqI9m830/Cr+k9g==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOHVEbm15TzZ4RHYwTTRj
            QWpSeURleUQyNWpvV0xnSUM3T1ROYTJSTFJvCnkrNEhuL09Hd0F3eTVISC9nQzZC
            M1duRHpsQy9WVUd4bUx4eDlYRWhRalUKLS0tIGpkZG5ReGk3OGJqWXN4VFRaWGha
            ZXlLSnJoTm15a1dxT2JSMHg3ZnZVbWMKWPsvdi3xjK/Rl44BqcvdMsCkb0lXlkG4
            5uKbR5jXKGGE64/2tF+AYHCz3oWQn1BhJgiQPxfQx5y91OoiaelPgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T13:48:48Z"
    mac: ENC[AES256_GCM,data:t30YviV7wv3FsMhBifL947d7NcJiW7NHC1w+cZtVTxCSW2HU7nz5idzn9pYn804yqZaqH5/ovBBRifTZ3JWV66g7nWDl7KmG9nwyAiaMR5z9nl9Fc3Bpz3FZRjWxY0neiNnZnZOaBtRkRdnYWPl9WNEv6XnbZEno4V70xzHmM4A=,iv:qg/UIxaREmgeoYRf9684wEamiMI5Tz5EVZGd3a6GERk=,tag:ykzv2S72MWDcpwOiYoWnKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
