apiVersion: ENC[AES256_GCM,data:v7M=,iv:r2J93bNRHaJlYWGf3dhDE6t5/UlPab3W2RDuPms0Hu0=,tag:C0NrXxRBKMPvT2wW26QkGg==,type:str]
kind: ENC[AES256_GCM,data:0r3qUknG,iv:hBcw49GmZwUXBZwp3lw5j1E6ORQ2ZPSQKb+dc4jHnjs=,tag:OBsqPlNaimHEj/pZO2fnOQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+pZXrFpnqzCohpJ1BM6E,iv:9QQ1iw2uIqyeQvybinHjL0B91U6KnvqHYqeY0Xh55mQ=,tag:47wUop5l0QNPf9Fcc0nSLw==,type:str]
    namespace: ENC[AES256_GCM,data:PByOYhIZR3o=,iv:oBpMlVCKiXLAkEVfU8lGbVpCXv2Uz6ca316uLmgHv9U=,tag:L/hw8yc/ajoT6ZOLzPs6NQ==,type:str]
stringData:
    root-password: ENC[AES256_GCM,data:ZfJkEdI592uCfAgCaUVPWJHBXc/P,iv:GxYFzR0vjPv43nAkIjDMB9GNNE+0Tzf5gUGNa3a68ys=,tag:yq/ypMxPWTAsGgXZfxDlng==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOHVEbm15TzZ4RHYwTTRj
            QWpSeURleUQyNWpvV0xnSUM3T1ROYTJSTFJvCnkrNEhuL09Hd0F3eTVISC9nQzZC
            M1duRHpsQy9WVUd4bUx4eDlYRWhRalUKLS0tIGpkZG5ReGk3OGJqWXN4VFRaWGha
            ZXlLSnJoTm15a1dxT2JSMHg3ZnZVbWMKWPsvdi3xjK/Rl44BqcvdMsCkb0lXlkG4
            5uKbR5jXKGGE64/2tF+AYHCz3oWQn1BhJgiQPxfQx5y91OoiaelPgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:13:56Z"
    mac: ENC[AES256_GCM,data:CROWjC6m/dl8N9wtmQ4PXwrPiEw+77E9ugaHMUGl06e+75sICrh/lox+6OO8LSN0vrrEJ5nTLkfBd/ib5B9BpPoaI7b78Zg90WR+SOX7+MeSpS2Urq4VyVlMsyoFsj953n0ccfcaq1cDl9ipq6ucWHoj2Ad+WR1Da8WOvN5zvFc=,iv:AoLvLg6kr4enzuVYJAoZ3LcrcafppbOEqq7Jswqmfho=,tag:Kvhc4MWklmZXla1qP49Ymw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:O9c=,iv:3jDmwzRgBRaIojXIzq8oKehzEFFZAVA3GPoQunJGzIM=,tag:6OAPuQKDoRqJ7/wNGv+BCg==,type:str]
kind: ENC[AES256_GCM,data:vCU0ZueU,iv:mfCLWaIDgDC+QoZoxk57SjWGm9syJoMTc9bC63P8tOs=,tag:ubKITpMcCF1V1S4Dg+sRvw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zgaIgr3YpmFGBjzV490=,iv:cwdWIQXZTCSZcYQXCFnqxDA3F1mAKHmaB4Inl3w34TU=,tag:ZHqvrRMKq0zxOz+8FhAIZQ==,type:str]
    namespace: ENC[AES256_GCM,data:8DIZVH48/Xs=,iv:ZZXekog2/aQoJuif7ISV4/crbdjfMFx2iDvHv6KCNE4=,tag:sEUxVxrCk6mjQ6vl0L77Gw==,type:str]
stringData:
    access-key-id: ENC[AES256_GCM,data:43BlaijGU36SlIz1ah/ysql4drqfI3pLEU4=,iv:vjgMaArA8Hy5JZpCfzVRU75Qz5YDyLv5DpdQWPWxaDk=,tag:CHur2JGHuEd3MUq3hC/woQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:67PdEq0pSISzA17DuB6TVKx/bERvWCD/y4MhmN46Nj479kSLq58iCJ0bLHrR0KBpIAc3uLmM8XzteDbmlpIJPg==,iv:GP6vwMtxN147UtT8Khu5Lv1gxwIo/HnOhr6+Bd24ulc=,tag:5wnZEaGDIJ6jjuTNGQpEpQ==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOHVEbm15TzZ4RHYwTTRj
            QWpSeURleUQyNWpvV0xnSUM3T1ROYTJSTFJvCnkrNEhuL09Hd0F3eTVISC9nQzZC
            M1duRHpsQy9WVUd4bUx4eDlYRWhRalUKLS0tIGpkZG5ReGk3OGJqWXN4VFRaWGha
            ZXlLSnJoTm15a1dxT2JSMHg3ZnZVbWMKWPsvdi3xjK/Rl44BqcvdMsCkb0lXlkG4
            5uKbR5jXKGGE64/2tF+AYHCz3oWQn1BhJgiQPxfQx5y91OoiaelPgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:13:56Z"
    mac: ENC[AES256_GCM,data:CROWjC6m/dl8N9wtmQ4PXwrPiEw+77E9ugaHMUGl06e+75sICrh/lox+6OO8LSN0vrrEJ5nTLkfBd/ib5B9BpPoaI7b78Zg90WR+SOX7+MeSpS2Urq4VyVlMsyoFsj953n0ccfcaq1cDl9ipq6ucWHoj2Ad+WR1Da8WOvN5zvFc=,iv:AoLvLg6kr4enzuVYJAoZ3LcrcafppbOEqq7Jswqmfho=,tag:Kvhc4MWklmZXla1qP49Ymw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:kx4=,iv:8ndEQkH773KynNNzAHBhKF1k/xoOPNyNDCode4PgwbM=,tag:XPrFmFKq08yAsscOmiahtQ==,type:str]
kind: ENC[AES256_GCM,data:9sXiIAkK,iv:HPm+XBg/UnOnuaYWQTBvpO9CahKCVIakYR8nUVLQzoE=,tag:bpd+4lsbzu6zqt2JSAraWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UhnjVixj3waEXErFGWp6ew==,iv:HhQ0kK+ggCgmTugHAFdhIO7ibbpgTPiXmG3iX5/oAiM=,tag:4FyXrgK1JFdKGBTjjoJSWg==,type:str]
    namespace: ENC[AES256_GCM,data:aEIzO1cmawc=,iv:2n/EKZgjYFiidlGzMtQvIUXgpBfz12Hp/w+bFmv8D7I=,tag:57L7izg9cb4kl2oSvERtzA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:VbVmwDNJXwQb8RMQX8n0NtR/g9KP427zribJ1zU=,iv:2jcPSaKHwX3hgoMgdLGaeiFH3S+7NLNBQZGqgMwRh5A=,tag:TIxt2Wg4HOKvopF/7ubRpw==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOHVEbm15TzZ4RHYwTTRj
            QWpSeURleUQyNWpvV0xnSUM3T1ROYTJSTFJvCnkrNEhuL09Hd0F3eTVISC9nQzZC
            M1duRHpsQy9WVUd4bUx4eDlYRWhRalUKLS0tIGpkZG5ReGk3OGJqWXN4VFRaWGha
            ZXlLSnJoTm15a1dxT2JSMHg3ZnZVbWMKWPsvdi3xjK/Rl44BqcvdMsCkb0lXlkG4
            5uKbR5jXKGGE64/2tF+AYHCz3oWQn1BhJgiQPxfQx5y91OoiaelPgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:13:56Z"
    mac: ENC[AES256_GCM,data:CROWjC6m/dl8N9wtmQ4PXwrPiEw+77E9ugaHMUGl06e+75sICrh/lox+6OO8LSN0vrrEJ5nTLkfBd/ib5B9BpPoaI7b78Zg90WR+SOX7+MeSpS2Urq4VyVlMsyoFsj953n0ccfcaq1cDl9ipq6ucWHoj2Ad+WR1Da8WOvN5zvFc=,iv:AoLvLg6kr4enzuVYJAoZ3LcrcafppbOEqq7Jswqmfho=,tag:Kvhc4MWklmZXla1qP49Ymw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:fKo=,iv:7Fs/fOynMUL4zmdcqmb6wf8fNkoU3pR5qfW0zuSI4UQ=,tag:bWTzxIx1vU6HqRKBZe9hJA==,type:str]
kind: ENC[AES256_GCM,data:Of6rQdy8,iv:nPwM/Jfbj8+9VoJ1kzEzYEtAe4tBH7QGPYTZpmYtBpg=,tag:sZXojsrOS4+A7u1u8x0JDQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lC0cmnN2PHsUe7dqhIE/cg==,iv:hIRopci9Tn+G/oZpP1/EUifzPAgFKrOJDlPQkfeyp4U=,tag:YkKzIxVbUBR2WCVge6XlEg==,type:str]
    namespace: ENC[AES256_GCM,data:CSKMPhM1n2o=,iv:wRDBM+aoBgzjBGLXRBbpw6jVhlkgBMbP1aj+l3m8SHc=,tag:xSkGZhaTpIbM/VCuujkYGQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:P2EooFcnnYZdDIe8/vGKIj6w2PwUzHXMFhg=,iv:QyD4xphKdxOfQnkVOv1S+SQXKavEf6BuesQa0GMqCMg=,tag:bWk2uDaFnhJvTKotUrSiXA==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOHVEbm15TzZ4RHYwTTRj
            QWpSeURleUQyNWpvV0xnSUM3T1ROYTJSTFJvCnkrNEhuL09Hd0F3eTVISC9nQzZC
            M1duRHpsQy9WVUd4bUx4eDlYRWhRalUKLS0tIGpkZG5ReGk3OGJqWXN4VFRaWGha
            ZXlLSnJoTm15a1dxT2JSMHg3ZnZVbWMKWPsvdi3xjK/Rl44BqcvdMsCkb0lXlkG4
            5uKbR5jXKGGE64/2tF+AYHCz3oWQn1BhJgiQPxfQx5y91OoiaelPgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:13:56Z"
    mac: ENC[AES256_GCM,data:CROWjC6m/dl8N9wtmQ4PXwrPiEw+77E9ugaHMUGl06e+75sICrh/lox+6OO8LSN0vrrEJ5nTLkfBd/ib5B9BpPoaI7b78Zg90WR+SOX7+MeSpS2Urq4VyVlMsyoFsj953n0ccfcaq1cDl9ipq6ucWHoj2Ad+WR1Da8WOvN5zvFc=,iv:AoLvLg6kr4enzuVYJAoZ3LcrcafppbOEqq7Jswqmfho=,tag:Kvhc4MWklmZXla1qP49Ymw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:udM=,iv:bEEZq5J1O+aUZ2VFWakYHyEBe66/h7Zp4oUxuDBPT24=,tag:I2bN26k5XxBkyD8OM+N65g==,type:str]
kind: ENC[AES256_GCM,data:Y0EZfnu/,iv:n+XDZPmsJXlAjvusYjFLyE70OIHj6Ztc8wV1lHF+muQ=,tag:Wk+eIMCcQ9vf+kn11EZUPA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pEzk6bhq4LjJUOfPHA==,iv:jJYgE51+2dOZ2ft+x7zMW+eisYFkzd5v7+1fGjxNdbs=,tag:jwsTt/F21kRSf6EXtUANgQ==,type:str]
    namespace: ENC[AES256_GCM,data:3cqxOXlg7sM=,iv:xiIPQ9iNJFOnjbhp22x+cbGb15ju01vDwoc9d95biS4=,tag:hdZeQm+hT9nSDZ28oaVCDA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:gXNDL4PfRu3+q8bm438Z3l4TcB+rYyP2VQ==,iv:pXCIJu5c16ptdws1XewCYzsu3aK2SMLS/OPkjYWYwW8=,tag:vojPWZzyOabEo+WDGqHcRQ==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOHVEbm15TzZ4RHYwTTRj
            QWpSeURleUQyNWpvV0xnSUM3T1ROYTJSTFJvCnkrNEhuL09Hd0F3eTVISC9nQzZC
            M1duRHpsQy9WVUd4bUx4eDlYRWhRalUKLS0tIGpkZG5ReGk3OGJqWXN4VFRaWGha
            ZXlLSnJoTm15a1dxT2JSMHg3ZnZVbWMKWPsvdi3xjK/Rl44BqcvdMsCkb0lXlkG4
            5uKbR5jXKGGE64/2tF+AYHCz3oWQn1BhJgiQPxfQx5y91OoiaelPgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:13:56Z"
    mac: ENC[AES256_GCM,data:CROWjC6m/dl8N9wtmQ4PXwrPiEw+77E9ugaHMUGl06e+75sICrh/lox+6OO8LSN0vrrEJ5nTLkfBd/ib5B9BpPoaI7b78Zg90WR+SOX7+MeSpS2Urq4VyVlMsyoFsj953n0ccfcaq1cDl9ipq6ucWHoj2Ad+WR1Da8WOvN5zvFc=,iv:AoLvLg6kr4enzuVYJAoZ3LcrcafppbOEqq7Jswqmfho=,tag:Kvhc4MWklmZXla1qP49Ymw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:RHY=,iv:CHZj5bMOhKrBBmgjZB1UASl3MZY7K4H+EirUq0W10vY=,tag:pC0VQenLT4IGxEyNE7rHZA==,type:str]
kind: ENC[AES256_GCM,data:UHkUXH9O,iv:zLX0vCx9rIWGJ2WyUbtJ/oA2hTifIKv/VDbWtcxI98g=,tag:GaL+DIuHIUdwXLpX8DH+Rg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jGp6aV9HKTaeUgnBpn50YXM=,iv:NoBOJEPwaUB2nbSlxw3+yju64pU7IKoqpWNmw8a7wWI=,tag:FDYYggz/ryawhd6m55WVJg==,type:str]
    namespace: ENC[AES256_GCM,data:9gRx8zd8IkI=,iv:WuyT1IMcpE8ZUH6VextmrlNf3LwiaBlbeeVx9CdARGU=,tag:3CfS1pvcsuv8+vOssVCxcw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:BnbBJgN1HQ0L2820NpNWdoUR8GVN,iv:YfQoJtcS9QZckU3RB7tCHqShVIssA0yMULTKBxLupNc=,tag:hLqQJi/gqI9m830/Cr+k9g==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOHVEbm15TzZ4RHYwTTRj
            QWpSeURleUQyNWpvV0xnSUM3T1ROYTJSTFJvCnkrNEhuL09Hd0F3eTVISC9nQzZC
            M1duRHpsQy9WVUd4bUx4eDlYRWhRalUKLS0tIGpkZG5ReGk3OGJqWXN4VFRaWGha
            ZXlLSnJoTm15a1dxT2JSMHg3ZnZVbWMKWPsvdi3xjK/Rl44BqcvdMsCkb0lXlkG4
            5uKbR5jXKGGE64/2tF+AYHCz3oWQn1BhJgiQPxfQx5y91OoiaelPgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:13:56Z"
    mac: ENC[AES256_GCM,data:CROWjC6m/dl8N9wtmQ4PXwrPiEw+77E9ugaHMUGl06e+75sICrh/lox+6OO8LSN0vrrEJ5nTLkfBd/ib5B9BpPoaI7b78Zg90WR+SOX7+MeSpS2Urq4VyVlMsyoFsj953n0ccfcaq1cDl9ipq6ucWHoj2Ad+WR1Da8WOvN5zvFc=,iv:AoLvLg6kr4enzuVYJAoZ3LcrcafppbOEqq7Jswqmfho=,tag:Kvhc4MWklmZXla1qP49Ymw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
