apiVersion: ENC[AES256_GCM,data:jZ8=,iv:pgO5HpMFZ6b/O1QmruG124OxuDeuFtjOvpOEp/W9vu0=,tag:iaqy1klJJqpd0BJgDjinAQ==,type:str]
kind: ENC[AES256_GCM,data:QpWHmzR5,iv:YWB221XzzTfeZEVAg0pYaGYaVKCXu7y6c4Vy3pGMenc=,tag:abQdmgsh83N9J1cL/JUxMA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EmzTLqEFb75eYkgQvK5e7fRAVA==,iv:sXCAAzztkW0f1oTyd5W27kSXvystmDlI3Ypg8VkJHS0=,tag:OQEOdlzhUSyPQ2Jho8hT2A==,type:str]
stringData:
    wg0.conf: ENC[AES256_GCM,data:A06SxAeaBjocnz/FqOYfe0gsE/0sW9V/o8w0kg3dXOGIL2PKaF8K+s1T9hS3SuodI11ADEMb/nTIQ4TcoVCfcFEauqzHa6+eP3/+lx/GNUWriF+2p1VQXoGIkDk/cAnGWzGFL+E2UeuqnyH5znqPPtCCHjvxkdJtCjGUGE60uvAi9UNXR431QtDIck6voNhE1OL0iPK4KQQn/kgHC9Wy06d+jRjC0LBRBn1OwAoRb2eu5QBFg4yKtH9EIfwhAMJCV46w1p+NEo+bw1LSZWdDFr3fSD2iuUOVn+unlGpuY/GiOOmCD0NJvIu7uwdSbT2wmirFNHa257stZpzpv6Urli+KSVCULpwgNzuJcRDhRQFlyl6uht8MPj0PyyxjdvUGghPFbjKc7okKKFY9VhaqoSngKP3n7sDre4qPp6CODrM3Nu0bfwgxqGGcDWjF/wk=,iv:8EPrvRJZfiqCV8bIjk7F5rjGbDXr+Xjf+/ZoVBjcJ3Q=,tag:COCcH4YZR8E0BbsKpsMBDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWjBnOXVEWENtT0Y0UG01
            azMxcUFHWnkxSHU2RUxJL3pzOW5ETWxBWVJ3CmxzcU9VenVZYnNqTHQ4UEM3N29q
            NFpXT1hxdFl4cHY5aXpCQk1FTVF1UDQKLS0tIHZxUUNLL0NGQkxVQ3E3SllpYlJm
            a0JXRmpNbmhjUnpEQ3dhVFJ0VGhIaUkKLkM++GCd2IAmsPuzIGHqxt2GK3+FgrN0
            rJoCVi3SgrQI0SLiiyUsrssjUMDWNwvQMAIaomqzrSnXFqFFAmeACw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
    lastmodified: "2026-09-03T12:44:26Z"
    mac: ENC[AES256_GCM,data:WJS5K6Ss2auOlzoMkI7X73VWbSmzVI0kDUCYVD+7DHsmnJu3MaD4dIiuO+E4k/LUca4hB88Ah+d6Rvvv+38NcpKeWggWiBn9B2hh2IQl9/g0JcAs8TwuehDKs5ZL2x3Wzb0iE8S7cfT+BUA/+0MXGVqYrCV/uJUKnKIwoJNN6fY=,iv:8Y2mxowA/pTtNjrc2InSVWuTiPgBhCNz+zktGDwaZxo=,tag:oUOSQj3Xk2sBpXgoQ7zE+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
