apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
  namespace: database
data:
  garage.toml: |
    metadata_dir = "/var/lib/garage/meta"
    data_dir = "/var/lib/garage/data"
    db_engine = "lmdb"
    metadata_auto_snapshot_interval = "6h"

    replication_factor = 1
    compression_level = 2

    rpc_bind_addr = "[::]:3901"
    rpc_public_addr = "garage.database.svc.cluster.local:3901"
    rpc_secret_file = "/etc/secrets/rpc.secret"

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"
    root_domain = ".s3.garage"

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".web.garage"
    index = "index.html"

    [admin]
    api_bind_addr = "[::]:3903"
    admin_token_file = "/etc/secrets/admin.token"
    metrics_token_file = "/etc/secrets/metrics.token"
