apiVersion: ENC[AES256_GCM,data:l+c=,iv:+GYaUMUyg56l5FiN323EBSuYCOPwjYXN6lWU99ZQftg=,tag:ihKiXi2o+JSO5QKf7D3Sgw==,type:str]
kind: ENC[AES256_GCM,data:PJYZvSiz,iv:SOqw1WBf6Fs3YTRjOR8Vkqn5TM7ZfzZmVgutalN6+HY=,tag:unH93iTrkVqrva++sUpSEg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EHay9ea8WL1U1NwBtQ==,iv:cduTp09tCBJGXl+quzKDmBRcARC/o6HG2IqJvgtWKZI=,tag:O8OGwYm0qHyY+QXc2WcaoA==,type:str]
    namespace: ENC[AES256_GCM,data:NukBUiPOdzg=,iv:XKkv68PjJmgVg/msRvFjbAV3WTfhWd61CP53+OoKPb4=,tag:Zpx2aLLCNC9JcUpg5WM9hg==,type:str]
stringData:
    rclone.conf: ENC[AES256_GCM,data:U79sfQvOAOgw/w3McQwqzRwa1QYTYW9FVdIuSlXUaqouMJzExdrHWGww9FRHu9A6owd+X4VUJe3OdwwAXCAqBN846e/g2SxvZYzbHyRfl2OsuXW5Xi/LbOpDiPmqrHyRXTvM/ILZcELpJ56ZQmtzbXgFO6endq0txjzlc2/1Z/NORJyG7PDefOjfYj8h3FNbsjeR1GgwulAnYM/Lqb8eiYX0tMXGEavX00DIKAHKil1/VGeM7Y5ggkOEbV/Ye8faSZQiJh7R42BYH2sBRqpk7gkS5aM3q0yni10SLJI49bMtk9jNfZknyiIqZ4o9IINVqqibo313/yc9kXB9Hb9ZvFuDlVaXhCKxSfk9np2EzBQUx1WXzR8qinHRWeOeOkZTT5B85/CM5SlZk1jurnSH5vVnABzyOUHFYvm+JZzZa0/2OgR2KAic+BrAEtg/nfM2AJAtFCjpzVp7LBu1QfscJ7y0dfn9okq1mNxFeFaoPAVy7YDaIV+AVSGxCi8WfVNMzlFdCKD7MlEECatuYwaGETA7LaqpXZfEaEG9ymq7kRcylnZ8LAbw/lxxN84wEeJpoInQEdCy/ZlBkuA3rtsT1EnU1Ais7Hy+GKf6lSbyKqpFyZBkWl0vg/cCtzDHMt98L2IZpa466DNikFaMXR2+MNersxg2+idiMO91WMsXiHkFMJJb2SA=,iv:qXAD2eZiFFZbkBbroFUAuj9wnee2OOpBoosotFf83jE=,tag:FdjMMlUC+ab/0Rq8dzXNww==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbDcrZmVId0lmbTY5RzI2
            NmdBdEtWN0ROeEJvRUlNMHNGWm5KMDFvYlZRCjVuNWovK3o5WFlxVnQ5aTRNeTVB
            UWhnaTJIbGU0cGRvWm5FVDlLaWlhdDAKLS0tIG53c2w5NGxkNnVDdm5XQWppRzRD
            OEFXOGNqeEtmcnE1aEJOK0x2RWdYb1UKbLwKBwPTemjdJiQNMZlBnOtTKHL8AYnn
            cVV9pMOxEKSdtXgEEw7P95DFIt7xn4KzZCjiRHXZSlCo6YoqnlX9IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T14:45:15Z"
    mac: ENC[AES256_GCM,data:ooea0VVcYebFfhiO80S4yXVf9iUevoEcflp5lbUjawvMIBvobE+yIsGF5owqC9OIZXIQmi6nRbAUj4AhmFrnfDJG0D78/6st1FZ+Qt3O+6U2TCYzFV2QGszVfMmCvMaqbOuatL/tcsh9Qj7QQXgT7z1SRIDi1t3y1bmzVyqx0fg=,iv:NWpmorMNC0cCLwl33hTCWr/VVodIwT5Mo8bkSZYgtiU=,tag:KqjGjx0X2iyEea2XTKdvOQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:LcI=,iv:MGUSC5tC/CqyFWD3NUGiqX5bxL0Tr2nNyECWA4QyMNk=,tag:bJdFzED6PVkDp2K4sMxsGw==,type:str]
kind: ENC[AES256_GCM,data:RmVZJFOG,iv:ky7Y1L/srBFiL0bJtqWnfNyZcsUgt0JmFD7BN5hYDao=,tag:gfvJkaWpIYlxtRtELZXiEQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0PqmnOkkkOf2ANlXbfs=,iv:hjy36XiBAqlsgsSFvwOktNQNKW7x2q4+llMZ5Cs1+GU=,tag:vQUvE9dY74xJZZ2zxtg8+g==,type:str]
    namespace: ENC[AES256_GCM,data:ZdSSR1WdbqQ=,iv:yTbMh7JxZNJr0YdcnjCKOB1Ir0fG7QG4FX1W77nXHLc=,tag:ZWFMvN+cUq2i330XU6PhhQ==,type:str]
stringData:
    rpc.secret: ENC[AES256_GCM,data:DQPekmRsFH8lqbtPG6arOCWuB+ZrY4XUBtilQ57d5yZzUzrBfAKV9abXiDpVKAhLBjpD0Jzurm7zYo0qXjpx+w==,iv:v+j0ji7CYIbazKC8Et3ZEOf8z1hrDgllt+kQMYKx81s=,tag:sFJKe+VqYyFJoWajdGLNMw==,type:str]
    admin.token: ENC[AES256_GCM,data:IHiDX8ALOj+Am3iplvjwqjJWVlj/gaKWDzgg3ymqb+xz/4wy2UGhjIn4nLE=,iv:Xwhz4iKJjU7Nw6ljF3qo4NQGhlFPaDu/nUcHnfZa9io=,tag:OcnMgWfFHWApXvX6UKQRwQ==,type:str]
    metrics.token: ENC[AES256_GCM,data:EqDwqck/BLT1tcu5KumFI93lIAqPaAQ15ha9ZEMEcQkMQDuoQ7Q9XJD+Du8=,iv:eD+FD71d5HgC96TMZDgmv8KPpSCtgwuNWwhh9w78/Ps=,tag:lRiaoLaToDEnsUI2aFdpcw==,type:str]
sops:
    age:
        - recipient: age1j80wssnp7v6kxuga65pua3utmza4y50w243sntfyncynhp6fwpuqxkx7lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbDcrZmVId0lmbTY5RzI2
            NmdBdEtWN0ROeEJvRUlNMHNGWm5KMDFvYlZRCjVuNWovK3o5WFlxVnQ5aTRNeTVB
            UWhnaTJIbGU0cGRvWm5FVDlLaWlhdDAKLS0tIG53c2w5NGxkNnVDdm5XQWppRzRD
            OEFXOGNqeEtmcnE1aEJOK0x2RWdYb1UKbLwKBwPTemjdJiQNMZlBnOtTKHL8AYnn
            cVV9pMOxEKSdtXgEEw7P95DFIt7xn4KzZCjiRHXZSlCo6YoqnlX9IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T14:45:15Z"
    mac: ENC[AES256_GCM,data:ooea0VVcYebFfhiO80S4yXVf9iUevoEcflp5lbUjawvMIBvobE+yIsGF5owqC9OIZXIQmi6nRbAUj4AhmFrnfDJG0D78/6st1FZ+Qt3O+6U2TCYzFV2QGszVfMmCvMaqbOuatL/tcsh9Qj7QQXgT7z1SRIDi1t3y1bmzVyqx0fg=,iv:NWpmorMNC0cCLwl33hTCWr/VVodIwT5Mo8bkSZYgtiU=,tag:KqjGjx0X2iyEea2XTKdvOQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
