apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: database
spec:
  loadBalancerIP: 192.168.1.7
  ports:
    - port: 3900
      name: s3-api
    - port: 3901
      name: rpc
    - port: 3902
      name: s3-web
    - port: 3903
      name: admin
  selector:
    app: garage
    component: garage
  type: LoadBalancer
