apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: garage
  namespace: database
spec:
  selector:
    matchLabels:
      app: garage
      component: garage
  serviceName: garage
  template:
    metadata:
      labels:
        app: garage
        component: garage
    spec:
      containers:
        - image: docker.io/dxflrs/garage:v2.3.0
          imagePullPolicy: Always
          name: garage
          ports:
            - containerPort: 3900
              name: s3-api
            - containerPort: 3901
              name: rpc
            - containerPort: 3902
              name: s3-web
            - containerPort: 3903
              name: admin
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: config
              mountPath: /etc/garage.toml
              subPath: garage.toml
            - name: secrets
              mountPath: /etc/secrets
            - name: data
              mountPath: /var/lib/garage/data
            - name: metadata
              mountPath: /var/lib/garage/meta
      volumes:
        - name: config
          configMap:
            name: garage-config
        - name: secrets
          secret:
            defaultMode: 0600
            secretName: garage-secrets
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 25Gi
        storageClassName: longhorn
    - metadata:
        name: metadata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
        storageClassName: longhorn
